# Generated by Django 5.1.3 on 2024-12-05 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SOSMessage',
        ),
    ]
