# Generated by Django 5.1.3 on 2024-12-05 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_expiringtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExpiringToken',
        ),
    ]
