# Generated by Django 5.1.3 on 2024-12-05 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0002_alter_sosmessage_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sosmessage',
            name='latitude',
            field=models.DecimalField(decimal_places=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='sosmessage',
            name='longitude',
            field=models.DecimalField(decimal_places=0, max_digits=9),
        ),
    ]
